### PR TITLE
fixes on not nullable properties

### PR DESCRIPTION
**Pull request by ViniciusSossela**
primaryColor and defaultLabelStyle property has a nullable atribution, which is not supported

### CODE REVIEW

**Review by kendall-lu — APPROVED** [review]
This will fix my issue with build. Thanks

**Comment by ong-gtp** [comment]
> This will fix my issue with build. Thanks

Can you kindly share the progress on this?

**Comment by szainab** [comment]
Is there any update on this? it's a blocker for us!

**Comment by vasilich6107** [comment]
@szainab 
It is fixed in https://pub.dev/packages/flutter_awesome_select/versions/6.1.2-beta

**Comment by akbarpulatov** [comment]
Sorry, I was very busy in the last few month))) 🙏

**Pull request merged**
