### PR TITLE
Fix: list items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list.

### LINKED ISSUE #15: List items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list
List items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list. Rather the list disappears, or it does not refresh.
Issue, lets try to add a new item to the list, before adding there were 3 items, check the list items at the end, the items disappear, instead it should show 4 items:
BeforeFix

Doing the same activity with fixed version from PR https://github.com/akbarpulatov/flutter_awesome_select/pull/12, in the below example lets try to add a new item to the list, before adding there were 3 items, and after adding, the list shows 4 items:
FixedVersion

### PR DESCRIPTION
**Pull request by absar**
Fix: list items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list.
Correct spelling mistakes. 
Fixes #15

### CODE REVIEW

**Comment by akbarpulatov** [comment]
Can you open an issue first and describe with an example?

**Comment by absar** [comment]
Here is the issue: https://github.com/akbarpulatov/flutter_awesome_select/issues/15

**Comment by absar** [comment]
Issue is not fixed in the latest version, you should merge this PR to fix

**Comment by akbarpulatov** [comment]
Actually, you deleted your repo, I cannot reopen your PR without your Repo.

**Pull request closed without merging**
